apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-search-deployment
  labels:
    app: elastic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic
  template:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
        - name: elastic-8-4-0
          image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
          ports:
            - containerPort: 9200