version: '3.8'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    hostname: es01
    deploy:
      replicas: 1
    environment:
      - discovery.type=single-node
    ports:
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host
    volumes:
      - D:/Dev/devroot/elastic/es01/data:/usr/share/elasticsearch/data
    networks:
      - es-net

  kib01:
    image: docker.elastic.co/kibana/kibana:8.4.0
    hostname: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - es-net

volumes:
  data01:
    driver: local

networks:
  es-net:
    external: false
    name: es-net
    driver: overlay
    attachable: true