apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-data-volume-pv-claim
  namespace: elastic
spec:
  storageClassName: elastic-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi