apiVersion: v1
kind: Service
metadata:
  name: elastic-service
  namespace: elastic
  labels:
    app: elastic-search
spec:
  externalTrafficPolicy: Local
  ports:
    - name: elastic-http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: kibana-http
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    app: elastic-search
  type: NodePort