apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-data-volume
  namespace: elastic
  labels:
    type: local
spec:
  storageClassName: elastic-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/run/desktop/mnt/host/d/devroot/trace/elastic/data"
