apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pv-claim
  namespace: my-web
spec:
  storageClassName: web
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi