apiVersion: v1
kind: Service
metadata:
  name: my-web-service
  namespace: my-web
  labels:
    app: my-web
spec:
  externalTrafficPolicy: Local
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: my-web
  type: LoadBalancer